/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: scores.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "scores.pb-c.h"
void   astronaut_score__init
                     (AstronautScore         *message)
{
  static const AstronautScore init_value = ASTRONAUT_SCORE__INIT;
  *message = init_value;
}
size_t astronaut_score__get_packed_size
                     (const AstronautScore *message)
{
  assert(message->base.descriptor == &astronaut_score__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t astronaut_score__pack
                     (const AstronautScore *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &astronaut_score__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t astronaut_score__pack_to_buffer
                     (const AstronautScore *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &astronaut_score__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AstronautScore *
       astronaut_score__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AstronautScore *)
     protobuf_c_message_unpack (&astronaut_score__descriptor,
                                allocator, len, data);
}
void   astronaut_score__free_unpacked
                     (AstronautScore *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &astronaut_score__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   astronaut_scores__init
                     (AstronautScores         *message)
{
  static const AstronautScores init_value = ASTRONAUT_SCORES__INIT;
  *message = init_value;
}
size_t astronaut_scores__get_packed_size
                     (const AstronautScores *message)
{
  assert(message->base.descriptor == &astronaut_scores__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t astronaut_scores__pack
                     (const AstronautScores *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &astronaut_scores__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t astronaut_scores__pack_to_buffer
                     (const AstronautScores *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &astronaut_scores__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AstronautScores *
       astronaut_scores__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AstronautScores *)
     protobuf_c_message_unpack (&astronaut_scores__descriptor,
                                allocator, len, data);
}
void   astronaut_scores__free_unpacked
                     (AstronautScores *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &astronaut_scores__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor astronaut_score__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AstronautScore, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AstronautScore, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned astronaut_score__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = score */
};
static const ProtobufCIntRange astronaut_score__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor astronaut_score__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AstronautScore",
  "AstronautScore",
  "AstronautScore",
  "",
  sizeof(AstronautScore),
  2,
  astronaut_score__field_descriptors,
  astronaut_score__field_indices_by_name,
  1,  astronaut_score__number_ranges,
  (ProtobufCMessageInit) astronaut_score__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor astronaut_scores__field_descriptors[1] =
{
  {
    "scores",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AstronautScores, n_scores),
    offsetof(AstronautScores, scores),
    &astronaut_score__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned astronaut_scores__field_indices_by_name[] = {
  0,   /* field[0] = scores */
};
static const ProtobufCIntRange astronaut_scores__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor astronaut_scores__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AstronautScores",
  "AstronautScores",
  "AstronautScores",
  "",
  sizeof(AstronautScores),
  1,
  astronaut_scores__field_descriptors,
  astronaut_scores__field_indices_by_name,
  1,  astronaut_scores__number_ranges,
  (ProtobufCMessageInit) astronaut_scores__init,
  NULL,NULL,NULL    /* reserved[123] */
};
