/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: scores.proto */

#ifndef PROTOBUF_C_scores_2eproto__INCLUDED
#define PROTOBUF_C_scores_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _AstronautScore AstronautScore;
typedef struct _AstronautScores AstronautScores;


/* --- enums --- */


/* --- messages --- */

struct  _AstronautScore
{
  ProtobufCMessage base;
  char *name;
  int32_t score;
};
#define ASTRONAUT_SCORE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&astronaut_score__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _AstronautScores
{
  ProtobufCMessage base;
  size_t n_scores;
  AstronautScore **scores;
};
#define ASTRONAUT_SCORES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&astronaut_scores__descriptor) \
    , 0,NULL }


/* AstronautScore methods */
void   astronaut_score__init
                     (AstronautScore         *message);
size_t astronaut_score__get_packed_size
                     (const AstronautScore   *message);
size_t astronaut_score__pack
                     (const AstronautScore   *message,
                      uint8_t             *out);
size_t astronaut_score__pack_to_buffer
                     (const AstronautScore   *message,
                      ProtobufCBuffer     *buffer);
AstronautScore *
       astronaut_score__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   astronaut_score__free_unpacked
                     (AstronautScore *message,
                      ProtobufCAllocator *allocator);
/* AstronautScores methods */
void   astronaut_scores__init
                     (AstronautScores         *message);
size_t astronaut_scores__get_packed_size
                     (const AstronautScores   *message);
size_t astronaut_scores__pack
                     (const AstronautScores   *message,
                      uint8_t             *out);
size_t astronaut_scores__pack_to_buffer
                     (const AstronautScores   *message,
                      ProtobufCBuffer     *buffer);
AstronautScores *
       astronaut_scores__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   astronaut_scores__free_unpacked
                     (AstronautScores *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*AstronautScore_Closure)
                 (const AstronautScore *message,
                  void *closure_data);
typedef void (*AstronautScores_Closure)
                 (const AstronautScores *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor astronaut_score__descriptor;
extern const ProtobufCMessageDescriptor astronaut_scores__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_scores_2eproto__INCLUDED */
